### ISSUE TITLE
plotting ProductFunction

### ISSUE THREAD

**Issue by mattlukac** [kr-colab/product-space-FEM#1]
We need a plot() method in the ProductFunction class with a slice as an argument. For lower dimensions slice can be None and plot the full (e.g. 2D) function. Alternatively we can plot a slice of the function by providing a point p in one of the marginal spaces, which would plot F(x) = f(p, x).

**Comment by petrelharp** [comment]
Proposal is for 1d x 1d just write a plot method that uses meshgrid; for higher/other dimensions write a slice_x(f, x) operator that returns y \mapsto f(x, y) as a fenics function.

**Comment by mattlukac** [comment]
Closing this as it has been implemented. Given a ProductFunction `u` and some reference point to `p`, we can see a plot of F(x) = u(x, p) by calling  `u.plot(p)`
