### ISSUE TITLE
`InverseProblem.optimize( )` both modifies its input in place and returns it

### ISSUE THREAD

**Issue by petrelharp** [kr-colab/product-space-FEM#14]
This is confusing since it's not obvious that it's updated it in place; the easiest solution would be to just not return it at all.

**Comment by mattlukac** [comment]
I'll change `InverseProblem.optimize()` to return the tuple `(m_hats, results)` where `m_hats[i]` is the control value (as a numpy array) at the `i`th optimization step. 

A few tests that use this method should be updated accordingly.

**Comment by mattlukac** [comment]
Now, after optimization to view the final control one must first run `control.update(m_hats[-1])` before plotting.
