### ISSUE TITLE
scipy >= 1.8.1 causes a segfault

### ISSUE THREAD

**Issue by petrelharp** [kr-colab/product-space-FEM#21]
@silastittes has tracked it down to a change that happened [between 1.8.0 and 1.8.1](https://github.com/scipy/scipy/compare/v1.8.0...v1.8.1). This is puzzling, since not much changed there, except for their [unuran submodule](https://github.com/scipy/unuran/compare/993f84a70ea4788f85b2343eb6eaef2204e94ec1...a63d39160e5ecc4402e7ed0e8417f4c3ff9634cb). Debugging this seems daunting, but it might be a legit scipy bug.

Here is the script that causes the segfault: https://github.com/kr-colab/product-space-FEM/blob/daf7a4580dba504b622ca240c76d3c9949449f14/debug.py

**Comment by petrelharp** [comment]
But, we can ignore this for now because we have a requirements file that pins scipy earlier than this.

**Comment by silastittes** [comment]
I've narrowed the segfault down to this line https://github.com/kr-colab/product-space-FEM/blob/daf7a4580dba504b622ca240c76d3c9949449f14/product_fem/inverse_problems.py#L148

There was an edit to scipy minimize for v1.8.1 here 
https://github.com/scipy/scipy/commit/1a0ac2d463dbf76ad85dbfd29106533ef05a86c2

**Comment by silastittes** [comment]
This might be relevant but didn't read closely 
https://github.com/scipy/scipy/issues/14915

**Comment by silastittes** [comment]
Or this one https://github.com/scipy/scipy/issues/5102

**Comment by silastittes** [comment]
`method='BFGS'` (instead of `L-BFGS-B`) runs with `scipy==1.8.1` fwiw.

**Comment by petrelharp** [comment]
> Or this one https://github.com/scipy/scipy/issues/5102

That one looks promising. However, we're only using 125 parameters in that example, so I don't think it can be it? Oh, that's also with scipy 0.12.1.

**Comment by petrelharp** [comment]
ps. I got the number of parameters by sticking in 
```
        print(f"Optimizing using {method} on {len(m0.array())} parameters with arguments {args} and options {options}.")
```
just before the call to `opt.minimize`.

**Comment by petrelharp** [comment]
We're not doing constrained optimization, so no need to use L-BFGS-B instead of BFGS!

**Comment by silastittes** [comment]
Awesome! I’ll play around with the versions for Python and scipy in the conda yml a bit more and make sure that switch clears up the segfault for other versions. Want me to make a small PR with the tiny updates after that?

**Comment by petrelharp** [comment]
Sure! I notice that `BFGS` doesn't have the `ftol` and `maxcor` options, but probably it has an option that's similar to `ftol` at least; perhaps we should stick that in.

**Comment by silastittes** [comment]
Cool. Happy to modify that. Does fixing the method to be BFGS seem like the right move, or should it keep option to use other methods?

**Comment by petrelharp** [comment]
I think we might want to try other ones out. Maybe we should throw an error if it's "L-BFGS-B", though?
